apiVersion: v1
kind: Service
metadata:
  name: mysql-lb
  annotations:
    metallb.universe.tf/address-pool: sandbox
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
  type: LoadBalancer
